---
- name: webserver setup
  hosts: webservers
  become: yes
    # vars:
    # dbname: electric
    # dbuser: current
    #dbpass: tesla
  tasks:
    - debug:
        msg: "the db name user and pass is {{dbname}} {{dbuser}} {{dbpass}}"
    - name: install httpd
      ansible.builtin.yum:
        name: httpd
        state: present
    - name: start service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: yes      
- name: DBserver setup
  hosts: dbservers
  become: yes
  vars:
    dbname: electric
    dbuser: current
    dbpass: tesla
  tasks:
    - name: install mariadb-server
      ansible.builtin.yum:
        name: mariadb-server
        state: present  
    - name: install pymysql
      ansible.builtin.yum:
        name: python3-PyMySQL
        state: present  
    - name: start mariadb-server
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: yes  
    - name: Create a new database with name 'accounts'
      community.mysql.mysql_db:
        name: "{{dbname}}"
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock
    - name: Create database user with name 'bob' and password '12345' with all database privileges
      community.mysql.mysql_user:
        name: "{{dbuser}}"
        password: "{{dbpass}}"
        priv: '*.*:ALL'
        state: present
        login_unix_socket: /var/lib/mysql/mysql.sock      
