---
- name: Proviosioning servers
  hosts: all
  become: yes
  tasks:
   - name:  see
     debug:
        msg: "The ansible_distribution value is: {{ ansible_distribution }}"
   - name: Install ntp agent on centos
     yum:
       name: chrony
       state: present
     when: ansible_distribution == "CentOS"
   - name: install ntp agent on ubuntu
     apt:
       name: ntp
       state: present
     when: ansible_distribution == "Ubuntu"
   - name: Start service on centos
     service:
       name: chronyd
       state: started
       enabled: yes
     when: ansible_distribution == "CentOS"    
   - name: Start service on ubuntu
     service:
       name: ntp
       state: started
       enabled: yes
     when: ansible_distribution == "Ubuntu"    

